### ISSUE TITLE
KeyError using checkKey()

### ISSUE THREAD

**Issue by granitepenguin** [bbrzuszk/pythonGraphics#18]
Seeing this while trying to use checkKey to handle some logic.

    while key is not 'space':
        key = win.checkKey()

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/drock/PycharmProjects/ringsoftron/graphics.py", line 451, in keyReleaseHandler
    self.keys.remove(e.keysym)
KeyError: 'space'

**Comment by granitepenguin** [comment]
seeing a similar issue with getKey() where most keys are either not getting picked up at all, or are throwing the same KeyError.  What's really weird is basically all alphanumeric keys are not getting picked up, but keys like Tab, Shift, arrow keys, Return appear to work fine.

**Comment by n-l-i** [comment]
yeah I noticed there were a couple of things wrong with it that made it not behave as specified, think I managed to solve most of them and included in my merge request.

![50B8F1C3-83DD-46D5-86F0-862D070E9315](https://user-images.githubusercontent.com/57808975/81485778-12e11000-9250-11ea-9c10-267996b73288.jpeg)

**Comment by granitepenguin** [comment]
tried out your changes, the key checking definitely works a lot better.  I'm getting reliable response from it for getKey.  I still have to try out some checkKey stuff, but so far much improved.
